# Generated by Django 3.1.7 on 2021-02-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamrin',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='tamrin',
            field=models.ManyToManyField(to='users.Tamrin'),
        ),
    ]
