# Generated by Django 3.1.7 on 2021-02-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210222_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='score',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
