# Generated by Django 3.1.7 on 2021-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210307_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='tamrin',
            field=models.ManyToManyField(to='users.Tamrin'),
        ),
    ]
