# Generated by Django 3.1.7 on 2021-02-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210224_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='medias/videos')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
