# Generated by Django 3.1.7 on 2021-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_responder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='document',
            field=models.FileField(default='No file', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vids',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
