# Generated by Django 3.1.7 on 2021-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210228_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='document',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
